# Generated by Django 3.2.13 on 2022-07-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220629_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('spanish', 'Spanish'), ('polish', 'Polish'), ('portuguese', 'Portuguese'), ('greek', 'Greek'), ('italian', 'Italian'), ('turkish', 'Turkish'), ('french', 'French'), ('moroccan', 'Moroccan'), ('british', 'British'), ('german', 'German'), ('austrian', 'Austrian'), ('lebanese', 'Lebanese'), ('caribbean', 'Caribbean'), ('indian', 'Indian'), ('thai', 'Thai'), ('japanese', 'Japanese'), ('chinese', 'Chinese'), ('mexican', 'Mexican'), ('american', 'American'), ('other', 'Other')], max_length=50),
        ),
    ]
