# Generated by Django 3.2.13 on 2022-08-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Spanish', 'Spanish'), ('Polish', 'Polish'), ('Portuguese', 'Portuguese'), ('Greek', 'Greek'), ('Italian', 'Italian'), ('Turkish', 'Turkish'), ('French', 'French'), ('Moroccan', 'Moroccan'), ('British', 'British'), ('German', 'German'), ('Austrian', 'Austrian'), ('Lebanese', 'Lebanese'), ('Caribbean', 'Caribbean'), ('Indian', 'Indian'), ('Thai', 'Thai'), ('Japanese', 'Japanese'), ('Chinese', 'Chinese'), ('Mexican', 'Mexican'), ('American', 'American'), ('Other', 'Other')], max_length=50),
        ),
    ]
